### ISSUE TITLE
中间件用法的小疑问

### ISSUE THREAD

**Issue by ethanvs** [ikcamp/koa2-tutorial#29]
为什么每次刷新浏览器, 所有中间件都会执行两次? 

效果如下:

![](https://zy1024.github.io/node-koa2/static/images/issues.png)

**Comment by BruceCham** [comment]
@zy1024  每个请求过来，都会经过中间件一层层过滤。你执行时候，会发起两个请求，一个是请求 『你要访问的地址』，另外一个请求是常见的图标『favicon.ico』。对服务器来说，所有的请求（包括URL、接口和静态资源：图片、js、css等），都属于资源，同等对待

**Comment by zy1024** [comment]
懂了, 多谢啦.  koa-router中引用jquery的ajax请求方式, 类型都使用method参数, 应该是type的.
