### ISSUE TITLE
视频体验不是很好呀

### ISSUE THREAD

**Issue by ishowman** [ikcamp/koa2-tutorial#31]
很感谢免费录制这系列的视频！但学习过程感觉有2点体验是很不好的。
- 视频很模糊
- 腾讯视频的体验很不好，必须用flash，而且不支持调速度。建议换b站吧，html5播放器和可调节播放速度还是很赞的

**Comment by BruceCham** [comment]
@ishowman 
视频这块体验上确实有点不顺，跟资源有关，而且各网站都带有广告。目前我们已经在迁移到另外一个视频网站，`没有广告`，`视频更清晰`  [视频地址 cctalk站](https://www.cctalk.com/m/program/1511435758606912)

**Comment by mqhe2007** [comment]
@BruceCham 不知道为什么，CCTalk的视频我这里无法播放，还是推荐传入B站，毕竟在视频方面，B站应该是很专业的。

**Comment by PeterChen1997** [comment]
十分感谢分享教学视频，CCTalk播放无法拖动进度条，推荐上传B站
