### ISSUE TITLE
感谢！！！

### ISSUE THREAD

**Issue by ruizer** [ikcamp/koa2-tutorial#37]
最近在学习node，但一直没找到合适的教程，直到发现此教程，就如教程介绍所说的：`亮点的课程设计，让你对 Node.js 豁然开朗`；真的让我豁然开朗、茅塞顿开、拨云睹日，宛如醍醐灌顶一般；感谢！感谢！感谢！

**Comment by WangShuXian6** [comment]
的确，目前看到的最好的koa教程。
