### ISSUE TITLE
扩展篇-【进行中，预计3、4月份出，敬请期待】

### ISSUE THREAD

**Issue by arronf2e** [ikcamp/koa2-tutorial#39]
扩展篇-这一块还继续出么

**Comment by zhouyao** [comment]
暂时停止更新，我们正在筹备新书《Koa与Node.js开发实战》，感谢支持

**Comment by arronf2e** [comment]
@zhouyao 期待

**Comment by ricosmall** [comment]
满满的期待扩展篇，尤其是静态资源处理这一块。

**Comment by 94dreamer** [comment]
那就把readme改下吧
扩展篇-【进行中，预计3、4月份出，敬请期待】

**Comment by WangShuXian6** [comment]
新书什么时候出？在哪发售？我想买。

**Comment by brokedream** [comment]
期待

**Comment by aaron-guoyx** [comment]
什么时候出新书，谢谢

**Comment by zhouyao** [comment]
目前在做最后的校对，预计８月份左右发售

**Comment by ricosmall** [comment]
@zhouyao 意思是这里的内容不会再更新了对吗？

**Comment by liuxsen** [comment]
实战，做一个啥项目？

**Comment by Coca-code** [comment]
koa-router ， 在判断 path时候， 每个中间直接await next();也可以， 是不是可以将 else()去掉？

**Comment by flyweights** [comment]
坐等更新，大大

**Comment by flyweights** [comment]
其实我觉得叫《Koa2与Node.js开发实战》会更好，更明确

**Comment by ManiuLtd** [comment]
请问下大佬们，这个后面还会更吗？git的源码好像被清空了啊

**Comment by lishuangli** [comment]
书我都买了,结果发现视频看不了~?什么情况哇

**Comment by BruceCham** [comment]
> 书我都买了,结果发现视频看不了~?什么情况哇

#44 试下这个应该可以解决

**Comment by zhouyao** [comment]
> 书我都买了,结果发现视频看不了~?什么情况哇

已经解决
