### ISSUE TITLE
視頻在海外無法觀看

### ISSUE THREAD

**Issue by kangchihlun** [ikcamp/koa2-tutorial#44]
請問可以上傳到其他的備援嗎?翻了牆還是看不了

**Comment by BruceCham** [comment]
@kangchihlun 试一下[B站](https://space.bilibili.com/36647965?spm_id_from=333.788.b_765f7570696e666f.1)或[youtube](https://www.youtube.com/channel/UCHDkNlCUjUQ6Y1kpFMSkIkQ)呢？
