### ISSUE TITLE
1

### ISSUE THREAD

**Issue by xwadh** [ikcamp/koa2-tutorial#45]
框架太简结了吧，是我找错代码了吗

**Comment by BruceCham** [comment]
@xwadh 您好，框架简单是指这个吗？https://github.com/ikcamp/koa2-tutorial/tree/bug-fix/css-name/code
这个教程制作的是一个简单实用的框架结构，更丰富的实例项目，可以参考下书中对应的完整实例 https://github.com/ikcamp/koa-miniprogram
