### ISSUE TITLE
文章视频为啥看不了了啊？

### ISSUE THREAD

**Issue by zilan830** [ikcamp/koa2-tutorial#54]
文章视频链接打不开。

**Comment by BruceCham** [comment]
[官网地址](https://camp.qianduan.group/koa2/2/0/0)  可以打开，有时候可能反应比较慢。
另外视频地址在youtube和b站上都有，直接搜索 `ikcamp` 即可 
文章也可以在[github](https://github.com/ikcamp/koa2-tutorial)上直接
